kind = "mobile"
previewPath = "/"
title = "The Toilet Paper Game"
version = "1.0.0"
id = "artifacts/toilet-paper-game"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/" ]
localPort = 24263

[services.development]
run = "pnpm --filter @workspace/toilet-paper-game run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/toilet-paper-game", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/toilet-paper-game", "run", "serve" ]

[services.env]
PORT = "24263"
BASE_PATH = "/"
